import { useEffect, useRef, useState, type FormEvent } from 'react';
import { listNoteShares, noteShareUrl, revokeNoteShare, type PersonalAuthMethod } from '../lib/api';
import type { NoteShareSummary } from '../types';
import { isDialogBackdropClick } from '../lib/dialog';
import { LocalSecretControl, personalMethodLabels } from './LocalSecretControl';

export function SettingsDialog({ open, username, deploymentMode, authMethod, onClose, onUpdateCredential, onUpdateSecurity }: { open: boolean; username: string; deploymentMode: 'global' | 'selfhosted'; authMethod: PersonalAuthMethod; onClose: () => void; onUpdateCredential: (password: string) => Promise<void>; onUpdateSecurity: (method: PersonalAuthMethod, secret: string) => Promise<void> }) {
  const dialog = useRef<HTMLDialogElement>(null);
  const [password, setPassword] = useState('');
  const [method, setMethod] = useState<PersonalAuthMethod>(authMethod);
  const [secret, setSecret] = useState('');
  const [message, setMessage] = useState('');
  const [busy, setBusy] = useState(false);
  const [shares, setShares] = useState<NoteShareSummary[]>([]);
  useEffect(() => { const element = dialog.current; if (!element) return; if (open && !element.open) element.showModal(); else if (!open && element.open) element.close(); if (open && deploymentMode === 'selfhosted') void listNoteShares().then(setShares).catch(cause => setMessage((cause as Error).message)); }, [deploymentMode, open]);
  useEffect(() => setMethod(authMethod), [authMethod]);
  const updateCredential = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setMessage(''); try { await onUpdateCredential(password); setPassword(''); setMessage('Mot de passe UVSQ mis à jour.'); } catch (cause) { setMessage((cause as Error).message); } finally { setBusy(false); } };
  const updateSecurity = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setMessage(''); try { await onUpdateSecurity(method, secret); setSecret(''); setMessage('Méthode d’accès local mise à jour.'); } catch (cause) { setMessage((cause as Error).message); } finally { setBusy(false); } };
  const removeShare = async (token: string) => { setBusy(true); try { await revokeNoteShare(token); setShares(current => current.filter(item => item.token !== token)); setMessage('Lien de partage désactivé.'); } catch (cause) { setMessage((cause as Error).message); } finally { setBusy(false); } };
  return <dialog ref={dialog} className="settings-dialog" aria-labelledby="settings-title" onClose={onClose} onCancel={event => { event.preventDefault(); onClose(); }} onClick={event => { if (isDialogBackdropClick(event)) onClose(); }}><button className="dialog-close" type="button" onClick={onClose}>Fermer</button><header><p className="eyebrow">Installation personnelle</p><h2 id="settings-title">Paramètres</h2><p>{username || 'Compte UVSQ configuré'}</p></header>{message && <p className="settings-message" role="status">{message}</p>}<section><h3>Mot de passe UVSQ</h3><p>À modifier seulement après un changement sur le portail officiel.</p><form className="settings-form" onSubmit={updateCredential}><input className="sr-only" tabIndex={-1} aria-hidden="true" value={username} autoComplete="username" readOnly /><label><span>Nouveau mot de passe UVSQ</span><input type="password" value={password} autoComplete="current-password" onChange={event => setPassword(event.target.value)} required /></label><button className="action-button secondary" disabled={busy}>Vérifier et enregistrer</button></form></section><section><h3>Accès à PulseNotes</h3><p>Méthode actuelle : {personalMethodLabels[authMethod]}.</p><form className="settings-form" onSubmit={updateSecurity}><label><span>Nouvelle méthode</span><select value={method} onChange={event => { setMethod(event.target.value as PersonalAuthMethod); setSecret(''); }}>{Object.entries(personalMethodLabels).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><LocalSecretControl method={method} value={secret} onChange={setSecret} label="Nouvel accès local" /><button className="action-button secondary" disabled={busy || !secret}>Modifier l’accès</button></form></section><section className="share-settings"><h3>Notes partagées</h3><p>Ces liens sont publics. Désactivez ceux qui ne doivent plus être accessibles.</p>{shares.length === 0 ? <p className="settings-empty">Aucun partage actif.</p> : <div className="share-settings-list">{shares.map(share => <article key={share.token}><div><strong>{share.moduleCode} · {share.label}</strong><small>{share.missing ? 'Note supprimée' : `Créé le ${new Intl.DateTimeFormat('fr-FR').format(new Date(share.createdAt * 1000))}`}</small></div><a href={noteShareUrl(share.token)} target="_blank" rel="noreferrer">Ouvrir</a><button type="button" disabled={busy} onClick={() => void removeShare(share.token)}>Désactiver</button></article>)}</div>}</section></dialog>;
}
