import { useEffect, useState, type CSSProperties } from 'react';
import { DistributionCurve } from '../components/EvaluationInsight';
import { fmt, formatDate } from '../components/UI';
import { loadPublicNoteShare } from '../lib/api';
import type { PublicNoteShare } from '../types';

export function SharedNote({ token }: { token: string }) {
  const [share, setShare] = useState<PublicNoteShare | null>(null);
  const [error, setError] = useState('');
  useEffect(() => { void loadPublicNoteShare(token).then(setShare).catch(cause => setError((cause as Error).message)); }, [token]);
  if (error) return <main className="shared-note-shell"><section className="shared-note-error"><p className="eyebrow">Partage PulseNotes</p><h1>Cette note n’est plus disponible</h1><p>{error}</p><a className="action-button primary" href="/">Ouvrir PulseNotes</a></section></main>;
  if (!share) return <main className="shared-note-shell"><section className="shared-note-loading" aria-live="polite"><span className="skeleton" /><span className="skeleton" /><span className="skeleton" /><p>Chargement de la note partagée…</p></section></main>;
  if (share.missing) return <main className="shared-note-shell"><section className="shared-note-error"><p className="eyebrow">Partage PulseNotes</p><h1>La note a été supprimée</h1><p>Ce résultat n’apparaît plus dans le relevé de l’étudiant. Le partage est conservé seulement pour signaler sa suppression.</p></section></main>;
  const { evaluation, stats, studentName, formation, semesterLabel, sharedAt } = share.payload;
  const difference = evaluation.note === null ? null : evaluation.note - stats.mean;
  const maxCount = Math.max(1, ...stats.distribution.map(item => item.count));
  return <main className="shared-note-shell"><article className="shared-note-card"><header><a href="/" className="shared-brand"><span>Pulse</span><strong>Notes</strong></a><span>Résultat partagé</span></header><section className="shared-note-identity"><p className="eyebrow">{semesterLabel || evaluation.moduleCode}</p><h1>{evaluation.label}</h1><p><strong>{studentName || 'Étudiant'}</strong>{formation && <> · {formation}</>}</p></section><section className="shared-note-score"><div><small>Note obtenue</small><strong>{fmt(evaluation.note)}<i>/20</i></strong>{difference !== null && <span className={difference >= 0 ? 'above' : 'below'}>{difference >= 0 ? '+' : ''}{fmt(difference)} face à la moyenne</span>}</div><dl><div><dt>Module</dt><dd>{evaluation.moduleCode} · {evaluation.moduleTitle}</dd></div><div><dt>Date</dt><dd>{formatDate(evaluation.date)}</dd></div><div><dt>Moyenne</dt><dd>{fmt(stats.mean)} / 20</dd></div><div><dt>Rang</dt><dd>{stats.rank} sur {stats.total}</dd></div>{evaluation.coefficient !== null && evaluation.coefficient !== 1 && <div><dt>Coefficient</dt><dd>×{fmt(evaluation.coefficient)}</dd></div>}</dl></section><section className="shared-note-chart"><div><h2>Position dans la promotion</h2><p>Distribution observée et position de la note.</p></div><DistributionCurve stats={stats} note={evaluation.note ?? stats.mean} large /></section><section className="shared-note-histogram"><h2>Effectifs par note</h2><div>{stats.distribution.map(item => <span key={item.value} title={`${fmt(item.value)} / 20 · ${item.count} étudiant${item.count > 1 ? 's' : ''}`} style={{ '--bar-size': `${Math.max(2, item.count / maxCount * 100)}%` } as CSSProperties} className={Math.abs(item.value - (evaluation.note ?? -1)) < .26 ? 'student' : ''}><b>{item.count || ''}</b><i /><small>{Number.isInteger(item.value) ? item.value : ''}</small></span>)}</div></section><footer><span>Export public PulseNotes</span><small>Partagé le {new Intl.DateTimeFormat('fr-FR', { dateStyle: 'long' }).format(new Date(sharedAt || share.createdAt * 1000))}. Ce document n’est pas un bulletin officiel.</small></footer></article></main>;
}
